### ISSUE TITLE
Tetres6 broken, needs to be deployed

### ISSUE THREAD

**Issue by gcochard** [jennazee/jennazee.github.io#7]
I'd file an issue on the tetres6 repo but it appears to have been fixed, just not deployed 😄

**Comment by jennazee** [comment]
What's the actual issue besides "broken"?

**Comment by gcochard** [comment]
Whoops sorry, Uncaught ReferenceError: SPEED_UP_AMT is not defined. This is when checking for completed lines. Looks like you fixed it in May.
